baseurl = "https://opensourcecities.github.io/munich/"
languageCode = "en-us"
title = "Open Source Cities - Munich"
theme = "osc-theme"

[params]
    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Open Source Cities - Munich"
    description = "A directory of companies, people, and projects that are Open Source and from Munich."
    fqdn = "https://opensourcecities.github.io"

    # The path must be relative to the static folder
    favicon = "favicon.ico"

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Munich"
        subtitle   = "A directory of companies, people, and projects that are Open Source and from Munich."
        buttonText = "Find out more"

    [params.contribution]
        guide = "https://github.com/opensourcecities/munich/blob/master/CONTRIBUTING.md"
        issue = "https://github.com/opensourcecities/munich/issues/new"

    # Footer
    [params.footer]
        # Conact
        [[params.footer.contact]]
            icon = "github"
            text = "@OpenSourceCities"
            link = "https://github.com/opensourcecities"

        [[params.footer.contact]]
            icon = "github"
            text = "@Munich"
            link = "https://github.com/opensourcecities/munich"

    # Google Analytics.
    googleAnalytics = "UA-XXXXXXXX-1"
